#config.yaml
server:
  host: "0.0.0.0"
  port: "8080"
  cors_origins:
    - "http://localhost:5173"
    - "http://localhost:4173"

logging:
  dir: "logs"

database:
  url: "postgres://erp_user:erp_pass@localhost:5432/dropship_erp?sslmode=disable"

jwt:
  secret: "cuancuan88"

# Credentials for calling Shopee Partner API
shopee_api:
  partner_id: 2011860
  partner_key: 464c4d4a626541646a6e46736873556952745372754d667866594f706978
  access_token: ""
  # long-lived token used to refresh access_token
  refresh_token: ""
  # optional base url override
  base_url_shopee: "https://partner.shopeemobile.com"
