#config.yaml
server:
  host: "0.0.0.0"
  port: "8080"
  cors_origins:
    - "http://localhost:5173"
    - "http://localhost:4173"

logging:
  dir: "logs"

# Maximum number of concurrent threads used by batch processes
max_threads: 5

database:
  url: "postgres://erp_user:erp_pass@localhost:5432/dropship_erp?sslmode=disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "1h"

# Redis cache configuration (optional - disabled by default)
cache:
  enabled: false
  redis_url: "redis://localhost:6379"
  password: ""
  db: 0
  max_retries: 3
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  default_ttl: "5m"

# Performance tuning configuration
performance:
  batch_size: 100
  slow_query_threshold: "2s"
  shopee_rate_limit: 1000
  shopee_retry_max_attempts: 3
  shopee_retry_delay: "1s"
  enable_metrics: true

jwt:
  secret: "cuancuan88"

# Credentials for calling Shopee Partner API
shopee_api:
  partner_id: "2011860"
  partner_key: "shpk714c6d706743744c55485053444d796555716673475a4d505a4f68756e53"
  access_token: ""
  # long-lived token used to refresh access_token
  refresh_token: ""
  # optional base url override
  base_url_shopee: "https://partner.shopeemobile.com"
