#config.yaml
server:
  host: "0.0.0.0"
  port: "8080"
  cors_origins:
    - "http://localhost:5173"
    - "http://localhost:4173"

database:
  url: "postgres://erp_user:erp_user@localhost:5432/dropship_erp?sslmode=disable"

jwt:
  secret: "cuancuan88"

# Credentials for calling Shopee Partner API
shopee_api:
  partner_id: ""
  partner_key: ""
  shop_id: ""
  access_token: ""
  # long-lived token used to refresh access_token
  refresh_token: ""
  # optional base url override
  base_url: "https://partner.shopeemobile.com"
