CREATE TABLE IF NOT EXISTS shopee_affiliate_sales (
    kode_pesanan VARCHAR(64),
    status_pesanan VARCHAR(64),
    status_terverifikasi VARCHAR(64),
    waktu_pesanan TIMESTAMP NULL,
    waktu_pesanan_selesai TIMESTAMP NULL,
    waktu_pesanan_terverifikasi TIMESTAMP NULL,
    kode_produk VARCHAR(64),
    nama_produk TEXT,
    id_model VARCHAR(64),
    l1_kategori_global VARCHAR(64),
    l2_kategori_global VARCHAR(64),
    l3_kategori_global VARCHAR(64),
    kode_promo VARCHAR(64),
    harga NUMERIC,
    jumlah INTEGER,
    nama_affiliate VARCHAR(128),
    username_affiliate VARCHAR(128),
    mcn_terhubung VARCHAR(128),
    id_komisi_pesanan VARCHAR(64),
    partner_promo VARCHAR(64),
    jenis_promo VARCHAR(64),
    nilai_pembelian NUMERIC,
    jumlah_pengembalian NUMERIC,
    tipe_pesanan VARCHAR(64),
    estimasi_komisi_per_produk NUMERIC,
    estimasi_komisi_affiliate_per_produk NUMERIC,
    persentase_komisi_affiliate_per_produk NUMERIC,
    estimasi_komisi_mcn_per_produk NUMERIC,
    persentase_komisi_mcn_per_produk NUMERIC,
    estimasi_komisi_per_pesanan NUMERIC,
    estimasi_komisi_affiliate_per_pesanan NUMERIC,
    estimasi_komisi_mcn_per_pesanan NUMERIC,
    catatan_produk TEXT,
    platform VARCHAR(64),
    tingkat_komisi NUMERIC,
    pengeluaran NUMERIC,
    status_pemotongan VARCHAR(64),
    metode_pemotongan VARCHAR(64),
    waktu_pemotongan TIMESTAMP NULL
);
