ALTER TABLE shopee_order_details
    ALTER COLUMN checkout_time TYPE TIMESTAMP USING to_timestamp(checkout_time),
    ALTER COLUMN update_time TYPE TIMESTAMP USING to_timestamp(update_time),
    ALTER COLUMN pay_time TYPE TIMESTAMP USING to_timestamp(pay_time),
    ADD COLUMN actual_shipping_fee_confirmed BOOLEAN,
    ADD COLUMN buyer_cancel_reason TEXT,
    ADD COLUMN buyer_cpf_id TEXT,
    ADD COLUMN buyer_user_id BIGINT,
    ADD COLUMN buyer_username TEXT,
    ADD COLUMN cancel_by TEXT,
    ADD COLUMN cancel_reason TEXT,
    ADD COLUMN cod BOOLEAN,
    ADD COLUMN create_time TIMESTAMP,
    ADD COLUMN days_to_ship INT,
    ADD COLUMN dropshipper TEXT,
    ADD COLUMN dropshipper_phone TEXT,
    ADD COLUMN estimated_shipping_fee NUMERIC,
    ADD COLUMN fulfillment_flag TEXT,
    ADD COLUMN goods_to_declare BOOLEAN,
    ADD COLUMN message_to_seller TEXT,
    ADD COLUMN note TEXT,
    ADD COLUMN note_update_time TIMESTAMP,
    ADD COLUMN order_status TEXT,
    ADD COLUMN pickup_done_time TIMESTAMP,
    ADD COLUMN region TEXT,
    ADD COLUMN reverse_shipping_fee NUMERIC,
    ADD COLUMN ship_by_date TIMESTAMP,
    ADD COLUMN shipping_carrier TEXT,
    ADD COLUMN split_up BOOLEAN,
    ADD COLUMN payment_method TEXT,
    ADD COLUMN recipient_name TEXT,
    ADD COLUMN recipient_phone TEXT,
    ADD COLUMN recipient_full_address TEXT,
    ADD COLUMN recipient_city TEXT,
    ADD COLUMN recipient_district TEXT,
    ADD COLUMN recipient_state TEXT,
    ADD COLUMN recipient_town TEXT,
    ADD COLUMN recipient_zipcode TEXT;

CREATE TABLE IF NOT EXISTS shopee_order_packages (
    id SERIAL PRIMARY KEY,
    order_sn VARCHAR(64) REFERENCES shopee_order_details(order_sn) ON DELETE CASCADE,
    package_number TEXT,
    logistics_status TEXT,
    shipping_carrier TEXT,
    logistics_channel_id BIGINT,
    parcel_chargeable_weight_gram INT,
    allow_self_design_awb BOOLEAN,
    sorting_group TEXT,
    group_shipment_id TEXT
);

ALTER TABLE shopee_order_items
    ADD COLUMN item_id BIGINT,
    ADD COLUMN item_sku TEXT,
    ADD COLUMN model_id BIGINT,
    ADD COLUMN model_name TEXT,
    ADD COLUMN model_sku TEXT,
    ADD COLUMN model_discounted_price NUMERIC,
    ADD COLUMN weight NUMERIC,
    ADD COLUMN promotion_id BIGINT,
    ADD COLUMN promotion_type TEXT,
    ADD COLUMN promotion_group_id BIGINT,
    ADD COLUMN add_on_deal BOOLEAN,
    ADD COLUMN add_on_deal_id BIGINT,
    ADD COLUMN main_item BOOLEAN,
    ADD COLUMN is_b2c_owned_item BOOLEAN,
    ADD COLUMN is_prescription_item BOOLEAN,
    ADD COLUMN wholesale BOOLEAN,
    ADD COLUMN product_location_id TEXT[],
    ADD COLUMN image_url TEXT;
