DROP TABLE IF EXISTS shopee_order_packages;

ALTER TABLE shopee_order_items
    DROP COLUMN image_url,
    DROP COLUMN product_location_id,
    DROP COLUMN wholesale,
    DROP COLUMN is_prescription_item,
    DROP COLUMN is_b2c_owned_item,
    DROP COLUMN main_item,
    DROP COLUMN add_on_deal_id,
    DROP COLUMN add_on_deal,
    DROP COLUMN promotion_group_id,
    DROP COLUMN promotion_type,
    DROP COLUMN promotion_id,
    DROP COLUMN weight,
    DROP COLUMN model_discounted_price,
    DROP COLUMN model_sku,
    DROP COLUMN model_name,
    DROP COLUMN model_id,
    DROP COLUMN item_sku,
    DROP COLUMN item_id;

ALTER TABLE shopee_order_details
    ALTER COLUMN checkout_time TYPE BIGINT USING extract(epoch FROM checkout_time),
    ALTER COLUMN update_time TYPE BIGINT USING extract(epoch FROM update_time),
    ALTER COLUMN pay_time TYPE BIGINT USING extract(epoch FROM pay_time),
    DROP COLUMN actual_shipping_fee_confirmed,
    DROP COLUMN buyer_cancel_reason,
    DROP COLUMN buyer_cpf_id,
    DROP COLUMN buyer_user_id,
    DROP COLUMN buyer_username,
    DROP COLUMN cancel_by,
    DROP COLUMN cancel_reason,
    DROP COLUMN cod,
    DROP COLUMN create_time,
    DROP COLUMN days_to_ship,
    DROP COLUMN dropshipper,
    DROP COLUMN dropshipper_phone,
    DROP COLUMN estimated_shipping_fee,
    DROP COLUMN fulfillment_flag,
    DROP COLUMN goods_to_declare,
    DROP COLUMN message_to_seller,
    DROP COLUMN note,
    DROP COLUMN note_update_time,
    DROP COLUMN order_status,
    DROP COLUMN pickup_done_time,
    DROP COLUMN region,
    DROP COLUMN reverse_shipping_fee,
    DROP COLUMN ship_by_date,
    DROP COLUMN shipping_carrier,
    DROP COLUMN split_up,
    DROP COLUMN payment_method,
    DROP COLUMN recipient_name,
    DROP COLUMN recipient_phone,
    DROP COLUMN recipient_full_address,
    DROP COLUMN recipient_city,
    DROP COLUMN recipient_district,
    DROP COLUMN recipient_state,
    DROP COLUMN recipient_town,
    DROP COLUMN recipient_zipcode;
